### ISSUE TITLE
Release v0.0.8 with gmic-py 2.9.0

### ISSUE THREAD

**Issue by myselfhimself** [myselfhimself/gmic-blender#15]
Should have the speed optimization requested in #14

**Comment by myselfhimself** [comment]
The cross-platform zipped addon is downloadable from here: https://github.com/myselfhimself/gmic-blender/releases/tag/v0.0.8

**Comment by myselfhimself** [comment]
Hold on, recreating release.

**Comment by myselfhimself** [comment]
Release done and working well :)

**Comment by truegeorg** [comment]
Oh c'mon ( 2.92 please

**Comment by myselfhimself** [comment]
For what operating system?

út 9. 3. 2021 v 20:57 odesílatel truegeorg <notifications@github.com>
napsal:

**Comment by myselfhimself** [comment]
@truegeorg which operating system would you like gmic-blender to be released for ?
